name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.1.1 #lalal
  - databricks-cli # added to assist with errors
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - pip:
      - wandb==0.13.9
    