name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  - mlflow=2.0.1 #2.0.1 suggestion, #2.1.1 orig
  - databricks-cli # added to assist with errors
  - scikit-learn=0.24.1
  - matplotlib=3.6.2
  - pillow=8.1.2
  - pip:
      - wandb==0.13.9
